### ISSUE TITLE
Missing line in config.yml

### ISSUE THREAD

**Issue by Swirren** [ttryy/OpenBucket#1]
This text line does not appear in config.yml to allow changing it. Please add it, as I renamed the buckets to "Super Buckets" and this line needs to be updated.
![image](https://github.com/ttryy/OpenBucket/assets/64167426/d06fafb1-33d0-4582-9808-a8e06648b508)

Thanks!

**Comment by ttryy** [comment]
I added a config setting allowing you to change the text that appears if you get an OpenBucket Item.

**Comment by Swirren** [comment]
Thank you!
